local StoryBook = LibStub("AceAddon-3.0"):GetAddon("StoryBook")
local Story = StoryBook:NewModule('StoryBook_MyLittleDashie', 'AceEvent-3.0');

Story.Title = "My Little Dashie";
StoryBook.AppendList(Story:GetName(), Story);

function Story:OnEnable()
	Story.Content = {"\"My Little Dashie\" by ROBCakeran53",
"I live my life, one day at a time.",
"A good portion of those days are uneventful, always falling in the same routine: I wake up, walk to work, work, walk home, then bum around until I go to bed.",
"Some times I'll hang with my few friends, while other times I'll just play video games or watch My Little Pony: Friendship is Magic.",
"Every so often, something new and interesting happens: I meet an old friend, I find a dollar on the ground, or I get chased by a stray dog.Living in a dying city isn't very fun or interesting.",
"This city was once full of life and color, but now...",
"now most of the houses are sagging, the businesses sit empty and abandoned, and several open fields lay barren of the once great factories that helped drive the economy.",
"I had never seen this city during those times in person, but I have seen pictures.",
"My mother and father lived happy, and they could only wish the same for me growing up.Sadly, I cannot say I have achieved that wish of theirs.I've fallen into the same dull routine: Wake, work, sleep, repeat.",
"I do have some moments of bliss, but the daily struggles I go through outweigh the small moments of joy I have.",
"My Little Pony has helped, but it's still just another thing to give my hopes up on.",
"Every time I see the show, or one of the ponies on a fan site, I recoil a bit at the bright colors, the joyful faces of the ponies, and the peaceful scenery of their world.",
"It's so hard to look at that beautiful world, having it so close to my grasp; I reach out to touch it's warm colors and bright, smiling faces of the ponies.Only to be stopped by my computer screen.I snapped back to reality.",
"It gets to the point where I will simply shut down my computer and walk away.",
"I do that a lot, especially after my parents death.",
"I go for a walk.",
"When I feel sad, I walk.",
"When I feel tired, I walk.",
"When I feel like walking...",
"I walk.",
"Walking has become my second life in a sense; I spend at least half my day outside along the crumbling side-walks and decaying suburbs.I've seen people come and go.",
"I've seen buildings torn down, burned up, or have so much graffiti on its walls that its original color is unrecognizable.",
"I very rarely pass any other people on my strolls.",
"Most people don't like to look at their once beautiful city, their homes or former businesses.",
"I don't blame them.",
"In fact I envy them.",
"They saw this place with their own two eyes, seeing the buildings still standing tall and proud, the lawns freshly cut, the paved roads, and sidewalks still intact.The only thing I've ever seen that even comes close is my mother's paintings, each of them colorful scenes of this concrete world.",
"She started painting once everything crumbled beneath her feet, making the sad scenery before her look beautiful.",
"Her masterpiece is of an open field that yielded a parking garage.",
"Over it, she drew an amazing rainbow.",
"My favorite picture.",
"I guess that is part of why I like Rainbow Dash the most out of all the other ponies.",
"Her colors, the amazing sonic rainboom, all remind me of that picture.There have been times I wished I had my own Rainbow Dash, or more realistically a plushie of her, to curl up in bed with.",
"I've made an old Simba into a \"temporary\" replacement, until I am able to save enough money for one.",
"It helps, in a way.",
"Like holding it close will heal my wounds, my pain, and my sorrow.",
"My feet, after countless hours of walking in my old shoes, pulsate under the sheet, and all the while, I'll hold that stuffed animal harder than a mother protecting her child.",
"It's the only thing I can look at and feel true joy, even if it isn't physically the Rainbow Dash I want.It will have to do.Today, as usual, I walked to work.",
"It was the same shit, just a different day, watching the same people enter the store, grab their merchandise and pay, then walk out with bags in tow.",
"My shift ended after several hours of this.",
"I clocked out and started walking home.",
"I decided to use a different route this time, for a change in pace, a little something different from the normal path I walk.",
"This part of town was hit the worst; only a few houses still stand, and none of them occupied.",
"It truly is a sad sight to see.",
"Then again, it's really the only sight I see.",
"The only sight I'll ever see.Or so I thought.I was stopped by something unusual; a stray cardboard box in the middle of the sidewalk.",
"Now, living in this kind of area I see trash all the time.",
"Boxes, McDonalds cups, and plastic bags litter the streets and empty fields, but rarely will I see a cardboard box that isn't crushed in one way or another.",
"I noticed this particular box because it happened to be in my way.",
"During my younger years, I tried to do what I could for the community.",
"I'd pick up trash when I saw it, or I'd attempt to help my neighbors.",
"It was a losing battle.",
"Now-a-days, I'd given up any hope of cleaning this city, much less my neighborhood.",
"Now I'll just pass the trash by, letting it blow away in the breeze or sit there and decompose.",
"I let what's left of the \"people\" do their own things, since most of them don't care about anyone other than themselves.",
"Why should I be any different?I walked past the box, barely giving it a glance.",
"Nothing about it caught my attention right away.",
"I continued on, my home not far away now.",
"Upon arriving, I sat down down and played some games, attempting to push the box out of my mind.",
"I had little luck, as the box somehow managed to push it's way back in.",
"Time crept on by, and I soon found myself wanting to go for another walk.",
"I left the house and started down my usual route when I stopped.",
"What was it about that box that made it stick out in my mind?",
"I turned around, starting down the path I had taken to get home, the path that I only walk once in a blue moon.",
"Curiosity got the best of me, and I wanted some closure.Within minutes I found it, still sitting there, sad and alone among the broken concrete and over-grown grass.",
"It didn't move, it didn't stand out as if it were special.",
"It was an ordinary, brown cardboard box.",
"I didn't want to say I came out here for nothing, so I walked closer to it.",
"As I drew closer, however, I began to notice something inside.",
"It was brightly colored, multiple colors in fact, and was quite small.",
"Maybe the size of a few month old Labrador puppy.I stopped beside the box, and looked down at the colorful blob inside.This is where I currently stand: looking into the box at a small...",
"something.",
"No, I know exactly what it is, but my brain isn't allowing me to fully realize it just yet.",
"At first I want to say it's simply a toy, left to die along with all the other things in this block.",
"But then I saw it breathing.",
"In fact, it appears to be sleeping.",
"My hands are sweating, my breathing erratic, and I'm blinking my eyes trying to refresh my vision.Each time, the image stays the same.",
"Inside, is a sleeping...",
"filly...",
"Rainbow Dash.I kneel down, trying to get a closer look into the box.",
"I can't believe what I am seeing.",
"There is not a physical, mental, or extraterrestrial way how this could be here...how she could be here, in my gloomy, dark and horrid world.",
"I examine the box further, and on the side in simple pen says \"Give to good home.\"The first thought that runs through my mind, besides the initial \"Filly Rainbow Dash in a box\", is \"Who would give up a filly Rainbow Dash?\"My mind is now a mess of questions.",
"How did she get here?",
"Why is she here?",
"Why is she a filly?",
"Her flank is even barren of her cutie mark, meaning she is indeed a filly.",
"As I stand to stretch my tired legs, I accidentally bump the side of the box with my foot, and the inevitable occurs: she wakes up.She looks around, rubbing her face with a foreleg, trying to wake herself up.",
"At first all she sees are the brown walls of the box, but then she looks up to me.",
"Those large black eyes, along with the rose-colored rim around them, drive my heart to, as the meme goes, explode...",
"twice.",
"The sheer cuteness of it all drives me to kneel back down, and I can't hold back a smile.",
"I haven't smiled like this in years, since the last time me and my parents went out to the only remaining park in the area.Her eyes continue to stare at me, and I stare back.",
"I don't know what to say, or what to do, but I must start somewhere.\"Hi there.\"I speak, but she doesn't respond.\"Uh, what are you doing out here?\"She looks around, then back to me.",
"The more I study her, the more I realize she is really young; years younger than her filly appearance in episode twenty three.",
"She might not even be able to talk yet...",
"that is, if she even can talk in my world.",
"The fact that she is even existing right now has me reeling in confusion.",
"I return my attention back to her, and notice a small shiver of her body.",
"The fall season is here, and it can get pretty cold, especially around mid-September.",
"I'm not sure how to exactly tackle this situation; do I take her home?",
"Do I call someone?",
"Who would I even call?",
"I'm a closet brony, so none of my friends know about my love of the show.",
"I can't take her to a shelter...",
"that's a stupid thought in the first place.",
"Not only would it be a horrible sight, she might be taken off to some lab and experimented on or something just as equally horrible.",
"I have only one choice.She shakes once more as the cool air reaches her coat; her wings ruffle as she lays back down and huddles her legs closer to her body to keep warm.",
"That's the final straw, I can't take anymore.",
"I take off my own jacket, and reach down and pick her up.",
"I get the initial response I expected; fear.",
"She begins to squirm around, unsure what I'm doing to her.",
"She can't fly yet, but she still flutters her wings as in praying for a miracle to happen that she does magically take flight.",
"I set her into my jacket, wrap her up so that her head is sticking out, and hold her in my arm.",
"She continues to squirm, but then my body heat begins to finally seep through the thin jacket and she settles down.\"It's all right.",
"Lets get you somewhere warmer, huh?\"I smile again at her.",
"She looks up to me with much confusion in her eyes as she tries to process what is happening.\"Don't worry, I'm not gonna hurt you.",
"It's getting late, and you'll freeze out here.\"I think she understands me, for after I say those words her eyes return to their normal size, and she snuggles herself more comfortably inside my jacket.",
"She squirms a little, trying to get into a more comfortable position.",
"I can feel her hooves and wings poking me as she shifts.",
"Then, to top it off, she rests her chin onto my arm and lets out a deep sigh, closing her eyes to drift off to sleep.My heart explodes for a third time.The entire walk back, I keep an eye out for other people who could pass by me.",
"I don't want anyone else to see her.",
"I have no way of knowing how they would react.",
"As usual though, I don't see a single person.",
"It's midnight by the time I get home; fortunately for us both, I had turned on my porch light, otherwise I might have passed it.",
"Being one of the few occupied homes on the block meant a lot of darkness.",
"The city even stopped running power to street lights, so that made it all the more difficult.",
"I glanced down at the filly, who continued to sleep in the jacket as I carried her.",
"She was no longer shivering, and felt quite warm.I walk up to my porch, careful not to make too much noise as I get my keys out, unlock the two dead bolts, the master lock, and finally the door knob, and open my door.",
"It is dark inside, due to me leaving while it was still light out.",
"With a flick of a switch, the single bulb in the hallway comes to life, shedding some light into the living room.",
"Most of the furnishings are my parent's.",
"Then again, so is the house.",
"I became the owner of it after their passing, and have done what I can to keep it that way.Still with the filly Rainbow Dash in my arm, I walk into the living room.",
"As I pass my family portrait, I greet it with a \"Hello mom, hello dad.\" I know they aren't there, but knowing that they loved me, and that I love them, helps me stay sane, and to keep going in my miserable life.",
"As I enter the living room, I can feel stirring in my arm.",
"She had woken up, most likely when I turned on the light, and is now getting antsy.",
"With no idea what to do or how to tackle the situation, I set her down on the couch.Immediately she jumps out of the jacket and looks around, already investigating her surroundings.",
"I continue to watch her as she explores the couch, then continues to the coffee table.\"What are you doing here in my world?\"I didn't mean to ask that out loud, but it just sort of happens every now and then.",
"Only seeing my few friends once in a great while, I find myself talking to, well, myself a lot.",
"I don't own a pet, because that just means more money to dish out and I'm already struggling as it is.From my question, the only response is another blank look on her face.",
"That tells me she has no clue either.",
"Then again, what else should I expect from a filly that can't even talk yet.\"Are you lost?\"The moment the words left my mouth, her ears fall and she looks to the ground.\"Oh...\"The realization strikes that she has no clue what is going on, where she is, who I am, or anything else.",
"She's beyond the word \"lost\": she is misplaced.\"Well, until something happens, I guess you can...",
"stay with me.\"I see how she lifts her head up, ears starting to erect once again, and looks at me with worry.",
"My words don't sound that encouraging, so I throw on a smile as I speak.\"Don't worry.",
"I'm sure whatever brought you here will fix itself within time.",
"We just...",
"gotta wait.",
"Is that alright?\"I'm not sure why I asked that, but it seems to do the trick.",
"Her ears perk right up and she smiles.The next few hours are spent giving her the \"grand tour\" of my house.",
"Nothing amazing to see, and I avoid taking her into my bedroom out of fear that the large amount of dirty clothes would swallow her up.",
"Afterwords, I give her something to eat.",
"I break up some small carrots, and amazingly I discover she has some teeth.",
"Since she is still a filly, I wasn't sure if she could eat solid foods such as carrots yet.",
"Then again, she is from a cartoon so I don't know what is \"correct\" for her anyway.Satisfied with the food, she finds a comfy spot in my father's recliner and sits.",
"I don't mind, it's not like I sit in it.",
"I was never allowed to when he was alive, so why should that change even after his passing?",
"It's his chair.",
"But I'm not gonna be mean to the filly for not knowing that, so I let her sit where she is most comfortable.",
"I also give her a small blanket to wrap herself in, due to my house's current temperature.",
"It's not as cold as it is outside, but my furnace has had problems since before my parents passing.",
"There was a trick to fixing it, but that died along with my father.I must have fallen asleep at some point.",
"I honestly expected myself to be wide awake due to such an interesting event, but after the long hours at work and staying up to take care of Dash, my body had other plans.",
"I'm not sure how long I was out before I awoke, but it doesn't matter; as I close my eyes, I feel something against my side.",
"I look, and sleeping beside me is the small cyan filly; her rainbow mane and tail still, her head resting on the inside of my elbow.I know the meme gets old, but I must say it: my heart exploded again.Laying there, sleeping and curled up beside me had me smiling ear to ear.",
"Her gentle breaths are barely heard.",
"The hairs on her mane tickle my arm, but I hold back any movement to itch.",
"The warmth of her body against my stomach warms my already weak heart.",
"Though a few months isn't a long time, it's how long I have wanted a moment like this.",
"My own little pony, a Rainbow Dash plushie to sleep with and hold tight.",
"And now I have a real Rainbow Dash, a filly, sleeping at my side; content as though she's known me since birth.Right now, there is nothing else that matters to me.",
"My despair, my sore feet and painful heart all go unnoticed as nothing else can come remotely close to the feeling I have right now; this joy I am experiencing at this moment as I lay awake on my couch.",
"She is here.",
"She is real.",
"Right now, she is my little pony.",
"She is...",
"my little Dashie.It has been only four months since I brought the young Rainbow Dash into my home.",
"I've done what little \"research\" I could on the matter, but I have come to no conclusions.",
"I have no idea why she is here, and quite frankly, I don't even care anymore.",
"These few months with her have been the most amazing time of my life.",
"She has opened my heart up to love and joy, among other things.",
"Right now, she sits next to me on the couch as I watch television.She seems to enjoy the morning cartoons on the local stations, and I myself have come to enjoy them.",
"She acts much like a young child would.",
"Then again why wouldn't she?",
"Another amazing feat is she has been learning to talk.",
"I'm not much of a teacher, or for that matter a parent, but I am doing my best to help her learn to speak and read.",
"I don't know how, or even where to begin to attempt in teaching her to write.",
"From the show they did it with their mouths, but I will let that go for now.",
"Once she is a little older, if I even have her that long, I will do what I can to teach her.It used to be that a year would go by slowly.",
"I would look forward to the new year, in hopes of getting a fresh start.",
"Now though, I feel as if this year went by a little too quickly for me.",
"I've decided, since I have no knowledge of her actual birth-date, to make the day I found her her birthday.",
"September the seventeenth...oddly enough, that's the very same date that the second season of My Little Pony: Friendship is Magic aired last year.",
"I quit watching the show after Dashie came into my life.",
"There was no reason for me to continue, and honestly, I don't have much time to myself anymore.It would be hard to hide me watching the show, and even harder to explain the situation if she were to ever see it, especially at her current age.",
"She knew her name was Rainbow Dash, but I have come to calling her Pinkie's pet name of \"Dashie\", and she has no problem with it.",
"She can fully communicate with me now, as well as read English, and she's even starting to learn how to write with, you guessed it, her mouth.I tried to \"invent\" some devices for her hoof so she could write, but it seems writing with her mouth is more natural than moving her hoof around.",
"One thing now troubles me with her.",
"Every day she sits at a window, looking outside.",
"I'm not worried about her being seen by passerby's.",
"I'm on a dead end street, so that's the least of my worries.",
"Still, though she doesn't say anything to me yet, I can see the hunger for fresh air in her eyes.",
"I can't keep her in here her entire life.Ha...I keep talking like she is going to be here forever.",
"That isn't true.",
"One day, some day, she will return home, whether it'll be a simple \"poof\" and she's gone, or through some magical spell and Twilight shows up and takes her home to fix everything.",
"In my heart, I hope that never happens.",
"In my head, I know it will.",
"It's just a matter of when.I do hope to get her outside soon.",
"I've been checking out some of the abandoned lots and former parks on my walks to and from work, seeing where the best location would be to take her.",
"Oddly enough, it seems the park I had played at growing up is the best option.",
"That shall be it then, I shall take her to the park.",
"How will I get her there?",
"She's still relatively small, so she can be hidden inside a jacket or something.",
"Tomorrow is supposed to be a nice day, anyway.She did it.",
"After two years in my care, and having absolutely no knowledge of flight myself, I helped her learn to fly.",
"She's gotten quite big in only a couple years, and it was getting hard to hide her when we walked to the park.",
"I got so desperate to keep her hidden, I bought a dog costume for her to put on, so she could walk there unnoticed.",
"She was not happy.",
"So, I got some books from the library and read up on teaching birds to fly.I would have looked on the internet, but I fear she would become curious of it herself.",
"There are a lot of horrors on the internet, and she's not ready for it.",
"In hind sight it's bad enough she is experiencing television, but she has come to enjoy Spongebob and Nascar too much for me to take that away from her.Back to the flying.",
"I've been taking her to that old park for weeks, in hopes I could help her learn how to fly.",
"There is a large tree there, with branches sticking out over a sandbox.",
"The perfect spot for her to practice.",
"If she falls, and I can't catch her, at least she'll have something remotely soft to land on.",
"She fell a lot.",
"I knew she would fall a lot.",
"There were many scrapes, cuts, and bruises toward her goal, but finally, after many weeks of work, she flew.",
"It was only a short distance, about fifty feet, but she still did it.",
"She's a little scraped up, but she's beaming with pride.",
"Maybe now she could fly overhead, so that the few people on the ground don't notice her.",
"I'll have to see if she can manipulate clouds like she could in the show; it would make it much easier to take her places.",
"Then she can hide on a cloud as we go to the park.",
"Another thing that has been brought to my attention.",
"She asked me about having her own room.",
"I got thinking, and realized the house does have a spare bedroom, though my parents had filled it with my old school stuff from my younger years, as well as several of my old toys.",
"She might enjoy them, though she is getting older I'm not sure how entertaining they will be for her.",
"If she has her own room, I can get her her own things, so that she can feel somewhat normal.",
"She's pretty smart for a filly, and knows about the difference between our species, but she still knows nothing about her origin.",
"She is not ready yet; the only thing I can do is keep her happy.I only wish I had a way to buy her the things she wants.If you told me four years ago I'd be taking care of a cartoon, rainbow colored pony, I'd call you insane.",
"I probably am in all reality, but I don't care.",
"I'm happy.",
"She's happy.",
"Today is a day for celebration, for today, my little Dashie got her cutie mark.I honestly didn't know how to tackle that fact.",
"She didn't even know what it was until I explained it to her.",
"Now she's even more ecstatic than before.",
"It was a normal park outing, but this time she decided she wanted to see how high she could get.",
"I had limited her to how high she could fly, but honestly I can't do anything about what she does up there.",
"I can't fly, so the most I could do is tell her to be careful.Somewhere she got it in her head to see just how fast she could fly, probably due to her being a Nascar and, well, a general racing fan.",
"For some time she was trying to make up tricks and stunts of her own, giving them names.",
"I'd just sit on a bench I had fixed up and cheer her on.",
"No one was ever around anymore.",
"In fact, on that block, I think the last person left over a year ago.",
"There are rumors the entire area is going to be bought out by some company however, and all this turned into a large manufacturing area.",
"I don't know how I feel about that...",
"but it's not important now.",
"Right now, I'm so over come with joy that my Dashie now knows her place.",
"Granted this isn't her world, she is still the same Rainbow Dash from the show..",
"Regardless of how I raised her, she has that same spunk and attitude from the show.",
"And now, she has her cutie mark.Anyway, she climbed to quite a height in an attempt to gain speed from a fall.",
"Well, all the right things factored for her; how she positioned herself, her mental focus, and possibly me on the ground watching and cheering her on, but she did it.",
"She broke the sound barrier, and created a sonic rainboom overhead.Now, I didn't even imagine it was possible to accomplish such a feat in my world.",
"I knew you could break the sound barrier, but actually do the rainbow part too?",
"My mind is blown.",
"So, the initial explosion brought upon many broken windows and sent off car alarms in the next county.",
"I quickly rounded her up and we rushed home before anyone could arrive at the park.",
"I was lucky none of my windows were broken.The rest of the day was spent celebrating.",
"It just so happened today was her fourth birthday.",
"I have no way of knowing how old she actually was when I got her, so I just started over.",
"I would have bought a cake, but due to the boom all the businesses were closed and needed new windows.",
"So, we made a cake on our own.",
"Apparently the fan fiction writers got it right: she can't bake at all.",
"Granted I'm not the best myself, but it was still a mess.",
"But we had fun, she enjoyed herself, and she is happy.",
"Therefore, I am happy.Though that was her highlight of the day, mine was just moments ago.",
"She has now come accustom to sleeping in her own room versus with me out on the couch.",
"I actually stopped sleeping in my room, and kept her company in the living room up until recently.",
"Now I can sleep on my own bed once more, but I keep my door unlocked, so if she needs me, she can get me.",
"I had just tucked her into bed and told her goodnight when she said it.\"Goodnight daddy.",
"I love you.\"I haven't been on the internet in, what, three years now?",
"I don't know how the My Little Pony thing online is doing, or what memes are still alive or not.",
"But damn it all, I'm gonna say it cause it's true! My heart exploded twice! For the first time, not only did she call me daddy,  which she has done on occasion, but she even said...",
"\"I love you.\"For a moment, I didn't know what to say or what to do.",
"I've never been in this sort of situation before.",
"But I remembered what my mother and father used to do.",
"So, I leaned down and kissed her on the forehead and told her the same thing.\"Goodnight, my little Dashie.",
"I love you too.\"She smiled at me, then closed her eyes to sleep.",
"I walked out, turned off her light, making sure her Spongebob nightlight was on, of course, closed her door,  then sat down on the couch.",
"I haven't moved for an hour now, I'm so lost in thought.",
"The few times she had called me \"daddy,\" I didn't think anything of it.",
"I could picture why she called me that.",
"Being with her so much made me accept it as part of taking care of her.",
"But tonight when she said those three words, the realization finally sunk into my heart.",
"I am her daddy.She considers me her daddy.",
"And quite frankly, I consider her my daughter.",
"Even though we are of a totally different species, I still love her with all my heart.",
"And it has taken her to speak those words to me for me to finally realize that.",
"I think I have finally done it.",
"I have broken my hard shell that had formed when my parents died.",
"I've let a sweet little filly into my life.",
"I gave her a home to live in, food to eat, and now a daddy to love.",
"She has given me hope, love, compassion, and now something I thought I'd never utter: a daughter.I still speculate when the time is going to arise that she goes back to Equestria.",
"And each day it gets harder for me to imagine when that actually happens.",
"I just hope that she never forgets me, because I will never forget her.I believe Dashie is now at her full size.",
"Rounding in at about three feet tall, she is fully grown.",
"Though she is still only ten years old according to my math, I believe she is actually more along the lines of fourteen or fifteen possibly in actual years.",
"So, we celebrated five missed birthdays and officially moving day.",
"That's right, moving day.",
"We moved from my parents house, thanks to me finally saving up enough money, plus getting lucky at a casino.",
"We bought a nice house a hundred miles away from the city.",
"It's got a lot of open land, there isn't another house within five miles, and it's just me and her.Now she can fly around all she wants, whenever she wants.",
"She is truly happy, though she does miss the old park.",
"It's gone now, along with anything else left in the area.",
"A large business bought all the land up, flattened it, and built a large factory there.",
"It was an amazing boom to the economy, and people are starting to build homes again! I'm glad, but...",
"it just wasn't for us.",
"That amount of people would hinder her going outside, and I'm not going to force her to stay inside all day unless it's raining out.I've gotten a new job, one that pays much more than my old one.",
"Dashie even talked about getting a job, but then she remembered what I told her.",
"The look on her face was heartbreaking.",
"We were enjoying a cake we made, which I must add we have improved upon that skill, when she brought it up.",
"I jokingly said she can't due to her being a pony and I laughed.",
"She remained silent.",
"My god I'm horrible.",
"I...I just laughed because my daughter is different.I apologized for hours, and even though she says she understands, I know she is still hurt.",
"Lucky, I have a way to fix this.",
"Due to the sheer size of the property, it involves a lot of cutting of grass.",
"Tomorrow I will modify a lawn mower for her to use, so that she can have a job.",
"I'll even pay her, so that she can buy her own stuff if she wants.",
"Though I'd have to get it for her, still she can actually say she worked for something.",
"According to the show, she was a weather pony.",
"And I don't have her mess with mother nature unless it's a dire emergency, so there isn't really any job to be had there.I still can't believe I've had her for ten years now.",
"My god, time goes so fast...",
"I wish it would slow down, so that I could have more time with her.",
"I don't know when, but I have the sudden feeling our time together is running out.",
"All of this has been too good to be true.Today has to have been the worst time of my life, even more than when my parents died.",
"Due to events I could not prepare for, Dashie found out the truth before I could tell her myself.",
"She knows what she is, a made up cartoon character from a kids television show.",
"She is mad, no, upset beyond all thought.",
"She had locked herself in her room, but I know my daughter.",
"She didn't stay in there long.",
"She opened her window and flew off, probably into a tree to sulk in her sorrow.I'm a monster.I should have told her sooner, I just wasn't sure when would be the right time.",
"Now we are both suffering for my carelessness.",
"I thought getting cable would be a good thing, give her some more shows to watch, but what I didn't realize was that we got the HUB station.",
"I wasn't even aware it was still up, and find my surprise the show My Little Pony is still even AIRING! It had stopped at eight seasons, but still it was repeated.I remember I walked in from work with some groceries, set them into the kitchen, and walked into the living room.",
"That's when I saw it...\"YAY! SHE DID IT!\" Fluttershy had screamed, jumping with joy as Applejack, Twilight, and Pinkie Pie all sat on the clouds with dumbfounded looks on their faces.My heart sank...",
"I knew this episode...",
"I remembered this episode.",
"Even after seeing nothing for twelve years...",
"I still remember that damn episode.",
"In that episode, Rainbow Dash performs the sonic rainboom, much like how my Dashie had years ago.",
"At the time I was still holding my keys...",
"and I dropped them.",
"They clanged on the wood floor; if she didn't know I was home before, she knew now.\"How long...\" Dashie asked me, no emotion in her voice.\"I...\"\"How long have you known about this?\"\"I...\"Dashie turned to look at me.",
"She had been crying, and her mane was in even worse shape than normal.\"HOW LONG HAVE YOU KNOWN ABOUT THIS?!\"I couldn't help it...",
"a tear ran down my cheek as she yelled at me.",
"This was the first time in all these years she had raised her voice to me.And I deserved every bit of it.So, I sat down, turned off the television, and told her everything.",
"I told her about the show, about finding her, and answered any other questions she had for me.There were a lot.Most of them stemmed from the show, to which I simply told her what I truly believed.",
"That though she is the Rainbow Dash from the show, that she herself is a different pony from the cartoon.",
"I tried to explain it to her, but her bullheadedness took over as she continued to lash at me.I took it all.",
"I deserved it all.",
"I've been keeping that horrible secret from her for far too long.",
"She is now a fully grown mare, capable of taking care of herself if she were in Equestria.",
"Here, I treat her still like she was my little filly.",
"It's been wrong of me, but I couldn't help it.",
"I didn't want this to ever happen, but I knew it would.",
"I should have done what was right, but I didn't.",
"It was only a matter of time before she found out, and she knew she was different.After our argument, she flew upstairs into her bedroom, and slammed her door shut.",
"I checked on her an hour later, and no response told me she had flown off.",
"I can only hope that she comes back, or at least, if she doesn't, she stays away from any other people.",
"If anything, I hope some sort of portal opens up and she goes back to her world, and never has to think of me again.",
"All I can say to her at this point, is that I'm sorry.I'm so...",
"so...",
"sorry.It's been three days since Dashie left.",
"The night of her departure, I did something I hadn't done in a long time: I went for a walk.",
"I wasn't sure where I was going, or how long I walked, but that's what I did.",
"I walked.",
"Now, three days later I'm finding myself out here walking once again.",
"I've been out for roughly three hours, and though it is only five in the afternoon, it has grown dark.A storm is brewing, and soon I will be getting hit by the brunt of it.",
"I turn around to begin my walk home, though I don't rush.",
"My energy these past few days has been non existent, as I have barely eaten anything more than some toast.",
"I feel so lost as I walk through the woods that surround my home.",
"No, our home.",
"It is as much hers as it is mine, and nothing will change that.The rain has begun, but I do not quicken my pace.",
"I just walk, much like I had done so long ago.",
"The distant memories of all my pain and sorrow before Dashie begin to seep back into my mind.",
"I haven't had these thoughts in years.",
"The pats of water on the tree leaves help keep me distracted.",
"It's a peaceful sound, one you would never hear in the city.The rain is picking up as my shirt is now soaking wet.",
"I'm sure I will be sick tomorrow morning, but I don't care.",
"I've been sick for three days now; a mental illness that has been tearing me apart.",
"My daughter is somewhere out here, hurting, needing some comfort and warmth in this rain.",
"I wish I could be there for her, even though she may not want me to.",
"She may not ever want to see me again from how she acted.I don't blame her...",
"it must be such a horrible thing finding out your past like that.",
"I can't even imagine what it would be like.",
"I know Dashie is a strong mare, and she can pull through.",
"But I also know how she holds a grudge at times.",
"I'm not sure that, even if she did come back, she would ever forgive me.",
"Or more importantly, if I could even forgive myself.It's now pouring out here.",
"The tree canopies are barely holding back the torrential rain as I'm hammered by the water droplets.",
"I stop to look around, and find my bearings to return home.",
"I'm not lost; most of this area is easy to traverse once you get used to it.",
"It's just I'm also looking for Dashie as I walk.",
"It's the reason why I'm walking in the forest in the first place.I press on, keeping a steady pace through this rain.",
"Suddenly, I spy a large, thick tree.",
"Its stature sticks out amongst the rest, and from looking at the barely wet grass underneath I can tell its many branches are holding back even this hard rain.",
"I need to take a break, so I walk under the tree and sit down.",
"The grass is barely wet, with only a few small droplets making their ways down.This is the kind of tree I'd imagine Dashie would hide under in this rain.",
"I wish it to be true, but I saw no sign of her as I approached.I close my eyes, and lean against the tree hulk as I think about my life...",
"our life, together as a father and daughter.",
"We have grown so much as a family, and have been fortunate enough to have very few fights.",
"None of them were as heart-breaking as the one three days ago.I feel a tear running down my cheeks as I imagine Dashie's face again.",
"The anger in her eyes, mixed with the confusion, just tears me apart.",
"I want so badly to make things right, or go back in time and stop it from happening.",
"But I can't do either of those.",
"What's done is done.“I'm so sorry...”I speak out loud, not caring for no one is listening.",
"I'm alone in these woods, besides the wild-life.",
"In this rain they are hiding as well, and the ones that aren't are far from a being such as I.“I'm just so sorry, Dashie.”I continue to cry as I keep my eyes closed, and leaning against the tree.",
"The rain continues to pour around me.",
"An occasional drop hits my head, but I don't care.CrackI open my eyes from the sudden sound, and look to my left.",
"I'm shocked at what I see before me, looking at me with teary eyes herself.",
"Dashie, my little Dashie, covered in burrs and tree sap along her mane and tail, is standing a couple feet from me.",
"She is wet, with both rain and tears.",
"I hadn't heard her approach, then again being a Pegasus she was very quiet and light on her hooves.She doesn't speak, and instead walks over to me, not caring what noises she makes under her hooves.",
"I don't move; I just sit on the ground and watch with my own wet eyes.",
"She looked so horrible, and yet so beautiful at the same time.",
"Her coat would need a good cleaning, but that was the least of my worries.Without a word, she sits next to me, not making eye contact as she looks off into the woods.",
"I can only look at her, wishing to hug her tightly and never let her go again.",
"But I hold back, knowing that it would be too sudden.",
"Finally, she is first to speak.“I...",
"I heard you,” Her voice then got quiet as she whispers, “And I'm sorry too.”I simply smile through my tears; her stubborn attitude was still showing as she always had difficulties apologizing, “Dashie, you have nothing to be sorry about.",
"It's my fault, simple as that.”It seems my point doesn't get across, as she finally looks to me with a sorrowful face.“Dad.",
"Do...",
"do you still love me?”Now is the time to act.",
"I reach over and grab her, holding her in a tight hug.“Of course, Dashie.",
"I've always loved you.",
"I still love you, no matter what.",
"Not even a small fight such as ours could ever change that.”She returns the hug, as we sit there and cry together.",
"We continue to apologize, me for the truth and her for raising her voice and storming out.",
"After some time, the rain subsides while we remain under the tree.“Dad.”“Hm?”“Can we go home now?",
"I need a shower, bad.”I let out a chuckle, and she too laughs as I stand.",
"We make our trip back home; she is smiling again.",
"I am too.",
"I've been giving it some thought, and I think I shall give her her birthday present a little early.A ticket to the Indy 500.",
"Yes, I'm taking her to the Indy 500.",
"She can simply sit on some clouds and watch while I'm in the stands.",
"I didn't even have to get her a ticket, but she needs some sort of reminder of her visit.",
"I'm sure she will have a blast, and though I don't expect this to make everything right, I can only hope it cheers her up some.With some time, I'm sure she will relax and settle down about her being in the cartoon.",
"She's a smart mare, and knows she is real, not that made up pony from the cartoon.",
"I can only help push her to believing that, and hope she does the same to me.There is a point in every parents life when they have to let their child go.",
"Whether it be for the better or for the worst, it must happen at some point.",
"I now sit here in my living room, by myself, sulking over photographs of my distant memories of me and Dashie.",
"On her twentieth birthday, I had planned a special outing to go see a flight show.",
"As we prepared to leave, there was a knocking at the door.Never in the years we have lived there had anyone knocked at the door.",
"Hell, we hadn't even made arrangements if someone did show up.",
"I simply told her to go to her room while I took care of it.",
"Once I heard her door shut, calmly and collectively I asked who it was knocking, expecting some stranger possibly lost on his or her travels.",
"A female voice spoke in such a elegant, yet attention grabbing tone I felt myself listening to her with the utter most attention.",
"She asked if she may come in; a question I'd normally refuse within a heartbeat, and yet something about her voice was reminiscent.",
"I couldn't help but walk over and open the door.",
"When I first saw the figure standing on my porch, I wasn't sure if I was dreaming or hallucinating.",
"Standing there, was the radiant and majestic Princess Celestia.",
"I was at a loss of words; fighting both emotions of brony excitement which I had only felt when I first found Dashie, and emotions of sorrow for I knew what this meant.",
"She stood there another second looking at me; we matched each other in eye level, her body being the size of a nearly full grown horse.",
"I stepped back, and allowed her to enter.",
"What caught me off guard next, was the five other ponies that followed suit.",
"First Twilight Sparkle, then the rest of the gang: Applejack, Rarity, Fluttershy, and lastly Pinkie Pie bounced in.\"Ooooh, so this is what an alien house looks like on the insi- OH MY! YOU HAVE A KITCHEN! I'm starving, are you starving?",
"I can make us some-\"She was stopped by Applejack's hoof, \"Easy there sugarcube.",
"We're jus' here fer Rainbow, so we ain't got no time for any eatin'.\"Applejack's stomach growled, \"No matter how hungry we are.\"I still wasn't sure how to completely react to all this, but not wanting to be rude I offered some left overs, \"Uh, we have some left overs from dinner last night.",
"You're more than welcome to some.\"Pinkie took that as an \"ok\" and ran into the kitchen with much vigor.",
"It seemed I did not even need to tell her where anything was; she instantly knew where everything was placed.",
"Factor it to either dumb luck or it simply being Pinkie Pie...",
"I chose the latter.\"Ah'll go keep an eye on her,\" Applejack said, walking to join the hyper pony.",
"As she passed, she tipped her hat to me.",
"I was finding it odd the ponies were not more hesitant around a creature such as me.",
"Then again, the same could be said for myself, but having Dashie for fifteen years I grew used to having such a thing around me.",
"Now, I have five other ponies and a full sized goddess horse looking at me with the same amount of curiosity that I held for them.There was a moment of silence as I watched the two mares enter my kitchen and begin to rummage through my fridge.\"I'm quite surprised,\" Celestia began, \"I had expected a little more resistance to us entering.\"\"Why?",
"I know who you all are.\"Celestia nodded, \"Ah, so you do know then.\"\"That you are fictional characters from a childrens T.V show, then yes.",
"Otherwise why you are all here I've no clue.\"The last part I lied, hoping to keep my mind at ease.",
"I knew the reason, but I wanted to ignore it.\"Oh, I think you do know.\"My heart fell into the pits of my stomach.",
"I did know, and she was straight to the point about it.",
"During all these years, I had anticipated this moment, but as time drug on that thought slowly dispelled until it was just nothing more than a minor nip in my mind.",
"That's when it always happens, you know; when everything is finally perfect and you don't have to worry anymore.\"Um, excuse me sir,\" Twilight began, \"But from what we could figure out Rainbow Dash should be here.",
"Is she?\"I looked to the purple mare; I wanted to tell her no, but I knew it was fruitless.\"She's up stairs in her room.\"\"In, her room?\" Rarity asked surprised.\"Yes, Dashie is in her room.",
"I wasn't sure who was knocking and didn't want her to be spotted.\"\"Dashie?",
"My my, you're that friendly with her already?\" Rarity continued.I wanted to punch that pony so hard right then; how she responded insulted me, \"Friendly?",
"That's not even the beginning of it.",
"And I should be asking you ponies as to what the hell you did?\"Celestia raised a brow, taken back by my change of tone, \"You see, my student-\"\"I know who she is, get to the chase,\" I was very short with her.",
"As furious as I was, I wanted to know why they'd send Dashie as a filly to some other world.Twilight bit her lip, as her teacher continued, \"Yes, of course.",
"Ahem, she was working on a spell to help the weather team with some storm development.",
"Well, they made slightly too large of a storm, and when Twilight used her magic to try and dispel it, it shot a lightning bolt meeting her magic.",
"Rainbow Dash was unfortunate enough to be within reach of the blast, and it engulfed her and sent her to, well, here.",
"So, we are here to retrieve her, simple enough I'd imagine.\"Before I could answer, Dashie called from her bedroom, \"Dad?",
"Is everything alright?\"That second my heart stopped beating as I looked from pony to pony.",
"Each one's face was in pure shock and confusion.",
"They recognized the voice of their Rainbow Dash, but she said \"Dad.\"\"Uh...",
"'scuse me sugarcube,\" Applejack started, returning from the kitchen, \"did ah jus' hear Rainbow call ya \"dad\"?\"Before I could answer, Celestia started up again, \"Do you care to explain?\"I was lost; so many things were running through my mind at once.",
"There was only one thing I could do...",
"and I had to do it, but I knew I wouldn't like it.\"Go into the living room and make yourselves comfortable, I'll be right down with her.\"I didn't allow a response; I turned around and walked up the stairs slowly.\"Dad?\"\"Yea Dashie, I'm coming up.",
"We...\" I looked back down to the group of ponies as they watched me ascend, \"...",
"we need to talk.\"So that's what I did.",
"I told her who was down there, and that they were there to take her back.",
"She had seen the cartoon every so often after some time, and found the wacky adventures entertaining.",
"She had given up any thought that the Rainbow Dash in the show was her, and only viewed it as another cartoon.",
"As I talked to her, and explained that those very ponies she didn't believe in were downstairs, she brushed me off with some laughs.",
"She didn't believe me, and thought I was playing some joke on her.",
"So, I took her down into the living room.\"DASHIE!\" Pinkie shouted, jumping onto her cyan friend.Dashie was quick to shove the pink pony off, \"Hey, get away from me!\" She was taken back by the sudden amount of ponies filling our living room.",
"They all looked to her with worried expressions as to why she shoved her closest friend away.Pinkie's cotton candy mane went straight as she looked in confusion.\"You...",
"don't recognize me...",
"do you?\"\"No, or any of you,\" Dashie continued.",
"It hurt me in so many ways.",
"I knew these were her friends, but so many things have happened differently that she didn't know the truth fully.",
"And neither did they, so I had to explain to them.\"I...\" I started, \"Dashie, take a seat please so I can talk to them.\"She did just that, in her recliner.",
"The entire time she looked at all the ponies who occupied the couches and center rug in front of the fire place.It was time, but first I had to start with a question, \"How long ago was she sent over here?\"The question caught them off guard, but Twilight cleared her throat as she spoke, \"About fifteen days ago, why?\"I was speechless.",
"Fifteen days ago?",
"Shit, she's been with me for fifteen years! That means a day in their world meant a year here.\"Well,\" I continued, \"It's been a lot more time than that here.\"\"How long?\" Twilight asked.\"...",
"Fifteen years.\"All the ponies, besides Celestia, had their mouths agape.\"That don't es'plain why she don't know us,\" Applejack said.\"Well, that's the thing.",
"When I found her, she was...",
"a filly.\"\"Come again?\"\"From my math, I think she was no older than four or five years old.\"Now Celestia looked surprised.\"You mean to tell us, that you have been taking care of Rainbow Dash for fifteen years, since she was a small filly?\" she asked.I simply nodded, and looked over to Dashie who wore an expressionless look on her face.\"We...",
"she is...\" I started, but I couldn't hold back my tears any longer, \"I know it's not true...god, I wish it was, but-\"\"I understand, the ‘dad’ now makes sense,\" Celestia cut me off, holding a stern look about her face.",
"She was thinking, trying to piece together in her mind what had possibly happened.",
"I chalked it up to the magic, being unstable possibly reverted her in age.For a few moments it was quiet, besides the breathing of seven ponies and myself.",
"Finally, it was Dashie who broke the silence.\"So what's supposed to happen now?\"I looked to the princess, trying to read her face.",
"No matter how good I had gotten at reading Dashie's face, Princess Celestia had the best poker face I had ever seen.",
"I had no clue what she was thinking, or feeling at this moment.\"Well, it's quite simple.",
"Twilight?\" Celestia looked to her pupil, who instantly perked up hearing her name, \"Do you still remember that memory spell?",
"From the Discord incident?\"Twilight simply nodded, as she stood from the couch and hopped onto the floor.I knew what was going on, what Celestia had in mind.",
"She wanted Twilight to either erase her memories and start from anew.",
"Or, possibly, I hoped she just simply wanted to give Dashie her memories of their friendships and time in Ponyville.",
"I wasn't sure what to do, I felt it was right.",
"I knew it was right, and needed to be done.",
"I had been telling myself that for fifteen years as I waited for this moment.",
"But there was something I needed to say before it happened.",
"These ponies were going to take my Dashie away, and I had some words to speak before that could happen.\"No, wait please,\" I started.",
"Twilight stopped, and looked to the sun goddess, \"Just, give me a moment with her please.",
"All I ask, since...since this is the last time we'll see each other.\"I had given up holding back my tears, and at this point was openly crying.",
"The ponies could tell I was hurting, and Dashie didn't look to be faring too well either.",
"So, figuring it wasn't good to prolong the inevitable, I walked over to the chair Dashie sat in, knelt down to meet her eye level as I spoke.\"Dashie, my little Dashie.",
"I love you with all my heart.",
"You have done wonders to open me up from the man I once was.",
"You...\" I had to pause a moment, to settle down, \"...",
"you have brought me so much joy in my life that I can't possibly ever thank you for.\"At this point, Dashie too had begun to cry.",
"That only made it worse for me.\"These fifteen years we have had together, talking, playing, flying; all those have been so special to me.",
"I just want you to know, that I will forever love you.",
"It doesn't matter if we aren't biologically related, or of different worlds.",
"I don't care what you may ever think of me, or if you ever even remember me, but right now, you being my Dashie, I want you,\" I poked her on the chest, to physically show I was talking to her, \"to know that fact.",
"If there is ever a problem that happens, and you need me, don't hesitate to find a way to get me, okay?\"I tried to laugh, passing the last part off as a joke.",
"It worked, only slightly, as we both continued to cry.",
"I could also hear some sniffling from behind me; I could only picture Pinkie Pie crying much like she had at the end of the second episode in season one, after Luna and Celestia had been reunited.\"D-d-do I have t-t-to go d-d-daddy?\"It had been a few years since she had actually called me \"daddy.\" Most of the time it was simply \"dad\" or \"pops\".",
"It felt good, knowing she still cared for me enough to call me daddy, much like the first times she had said it to me, so many years ago.I simply nodded my head, as I stood up.",
"Before I could fully grasp my balance, she jumped up onto me and hugged me tight.",
"I could feel her tears on the back of my neck, and I returned the embrace.\"It's your actual home, Dashie.",
"You don't belong here.",
"You need to go back to where you belong.\"\"I belong here, with you!\"It hurt so much to say, but I had to keep her convinced that this was the right thing to do, \"No, you don't.",
"You are limited here, only able to fly around the house.",
"You have no friends, or other ponies to relate to.",
"I was only taking care of you until this time would come, but I never thought it would be this painful.\"It remained quiet for a few more minutes as we held each other tight.",
"She didn't fight back, or want to resist what was happening, which told me that she knew as well what must be done.\"I love you daddy...\"\"And I love you too, my little Dashie.\"We separated, as she lowered herself to the ground.At this point all the other ponies had tears flowing, even the goddess herself.",
"She had seemed quite smug about knowing what had happened, the time difference and such, but it was evident that the age difference was a shock.",
"She most likely had expected to find a thirty five year old Rainbow Dash, but instead found my twenty year old Dashie.Twilight stepped closer to Rainbow Dash, sniffling once before her horn glowed.",
"I knew what was coming, it hurt so much...",
"but I knew it was right.",
"It was what had to happen, for her, for her friends, and in a twisted way for me.",
"Now I could know she was actually going home, and would be around her friends and could fly where ever and when ever she wanted to, without any limitations.",
"She could enjoy friends company once more.\"Wait!\"I looked from the floor to Dashie, as she backed away from Twilight, \"Before I go, I want to get something.\"Before anypony or myself could protest, she flew up to her room.",
"She was quick, and returned with a shoe box in her front hooves.",
"I wasn't sure if she would be allowed to take anything back with her, and half expected the princess to protest.",
"But she remained quiet, allowing Dashie to quickly write down something on a piece of paper and set it on the coffee table.She looked back to me, still crying, but with a smile on her face.",
"I knew she had realized this was how it must end, and knew I knew that as well.",
"The box, from my guessing, was probably her most cherished items that she kept for if she had to leave.",
"Though it hurt me thinking about it, I hoped she had a picture of us.",
"Then again, I also hoped not, for she would be forced to remember me a world away, and that hurt just as much as everything else.\"I'm so sorry Rainbow Dash.\" Twilight started.",
"\"I...I honestly wish there was another way to do this.",
"I wish I didn't have to do this.",
"But...\"\"Can't...\" Dashie started, \"can’t he come with me?\"The stuttering in her voice told me she was simply speaking her mind, not actually asking the question.",
"Twilight shook her head, unable to keep eye contact with her friend as she cried before her.\"Rainbow Dash-\" Princess Celestia started, \"He cannot join you in our world much like how you cannot stay in his.",
"This was all never meant to be, and the world around us was not made to house you.",
"And yet...\" Celestia looked to me, smiling, then began to look around our living room.",
"All the photos of us together, all her knick knacks and belongings strewn around the room, \"...",
"and yet, something beautiful happened here.",
"Something I cannot explain in full.\"\"When I realized where you ended up, I expected the worst.",
"I figured you to be ruined, tainted and tarnished from this world's cruelty.",
"But now, I see that it's quite the opposite.",
"That here, this man that has raised you, shows me that you were in good hooves- Or, hands as it were.\"Dashie sniffed once, beginning to calm down as Celestia's words sunk in.Celestia then returned to looking at me, still smiling, \"I cannot speak for you, but from what I see in front of me, the amount of love you both share and have shared together, tells me that you raised her as if she was your own.",
"Even with the obvious differences, you still raised her un-biased as to her species, her origins.",
"You raised her as your daughter, which only makes this entire ordeal so much worse.\"I absorbed her words, as well as the other ponies in the room.\"So, I must say to you, dear sir, please do not hold my student accountable for this.",
"It was never her, nor anypony elses intention to cause this much hurt to either of you.",
"If you must blame somepony, I would ask you to blame me.",
"I am the one that helped bring them here, to take Rainbow Dash back to her home...",
"away from here.\"I just couldn't look at any of them.",
"My heavy breathing breaking down with sobs.",
"My mind was just going on her own, thinking back at all the things Dashie and I did together.",
"I took a deep breath as I spoke,\"...Just how could I blame somepony?",
"For sending Rainbow Dash here?”I sniffled, then cleared my throat as I continued.",
"I nearly choked up as I searched for the words to express myself.\"These have been the best 15 years of my life.",
"So, if anything, I feel quite the opposite; I wish to thank you, Twilight, and the rest of you.",
"Thank you, for what you did, though not intentional.",
"Thank you, for all that came out of this.",
"And finally thank you, for all my years, my life, and my love...",
"with Dashie.\" I tried to smile at Twilight between the sobs, but she looked on the edge of tears herself, and could only look away, before she cried herself.Celestia then stood from the rug she laid on, and walked over to me as I stood.\"No need for thanks, good sir.",
"Instead, I wish to thank you, for taking care of one of my little ponies.",
"She would have never made it without someone much like yourself.\"Celestia closed her eyes, and then leaned her horn towards me.",
"I didn't move; I wasn't sure what was going on as she touched her horn to my head.",
"I felt a sudden warmth rush through my body.",
"She drew her horn away, still smiling as she stepped back.\"Thank you.\"Then, another pony spoke up.\"Thank you, sir,\" Twilight added, finally able to speak through her tears.\"Thank ya,\" Applejack said.\"Thank you, darling, for caring for our Rainbow Dash,\" Rarity spoke.\"Um, th-thank you,\" Fluttershy quietly said.\"THANKS!\" Pinkie shouted, as she sprung up to me and hugged me.I couldn't help but laugh a little from her extrinsic attitude.",
"Better yet, the rumors on the internet were true; her mane did smell like cotton candy.I remained silent as I nodded, then looked back to Dashie, who also wore a smile on her face.The ponies all returned to Dashie as Twilight's horn began to glow once more.\"Are you ready now, Rainbow?\" Twilight asked again, returning to Dashie and starting her magic.She simply nodded, as she closed her eyes and awaited the inevitable.It seemed time slowed down as Twilight's horn approached Dashie's forehead.",
"My mind began forcing random memories of us together.",
"I can vividly remember the splashing of the bathtub from her bath times, before she showered herself.",
"I can still taste our many failed attempts at baking and cooking in general.",
"I still smell the outdoors from our times at the park, where she was able to spread her wings.",
"There were so many memories, that I simply had to shut off my brain so that I could keep myself focused on Dashie.A single tear ran down her left cheek, as I could see her eyes moving under her lids.",
"Her mind was doing the same thing mine was, forcing our fondest memories all at once, for this would be the last time we ever saw one another.Finally, Twilight's horn touched Dashie's forehead.",
"There was a bright light, and when I could see again they were all gone.",
"All the ponies had disappeared.",
"Through my tears, I sighed in relief.",
"It felt wrong, but it also felt right.",
"She was now the normal Rainbow Dash that belonged in Ponyville.",
"I stood in the living room for several more minutes, just staring blankly at the empty floor that Dashie had been standing at just moments before.",
"Then, I looked around the room and took notice at my surroundings; I noticed things were different.",
"Pictures that once held images of me and Dashie no longer hung from the walls.Many of the random personal items of hers were scattered around the living room were gone as well.",
"I was confused, so I ran up to her bedroom to look.",
"When I opened the door, what I saw instead of her Nascar and air show posters mixed with her bed and other furnishings...",
"was a simple office.",
"A cheap desk with a computer on it and an ugly looking potted plant.It took me some time to digest what I was experiencing, before I realized what must have happened.",
"It made sense, but it still stung me in my chest.",
"To make sure nothing happened between worlds, Celestia must have removed any existence of Dashie ever being here.",
"Being with me.",
"Fifteen years, all down the drain as her existence was wiped from the planet.",
"I felt as though all those years were for naught, wasted as I wouldn't be able to remember her.And yet...",
"my memories still lingered of her.",
"I could remember everything as if it were still as vivid as when they happened.",
"Then the thought clicked: she did something with her magic when she touched me with her horn.",
"Did...",
"did she protect my memories so that I would remember her?",
"Had she done the same for Dashie?",
"I walked back downstairs, and into the living room while I thought.",
"On the coffee table, sat a book.",
"I recognized it; it was my photo album.",
"I sat down on my couch, opened it up to the first page.",
"There, was my mother and father with me shortly after I was born.I continued to flip through them, looking at my own past.",
"There was a gap after my parents died, but to keep my mother's dream going I had picked it back up.",
"Making false pictures of happy times and enjoying my life to stick into her book of memories.",
"Then, I opened up to a piece of paper.",
"I picked it up, and immediately recognized the hand writing.",
"Or more correct, mouth writing.",
"I speculated this was what she had written down before she left.Dad,For fifteen years you took care of me.",
"For fifteen years you loved me, played with me, and made sure I enjoyed my life in a world not meant to house me.",
"I'm not a mare of many words, but even though I told you this in person, I felt you needed a written version of it so you will know it was all real.I love you daddy.",
"You helped shape me into the mare I am now.",
"I'm not sure what is going to happen, if I will remember any of this or not, but I want you to know that you did a darn good job of raising me, even if I was a bit stubborn at times and short with you during others.With Celestia's permission, I hope to allow you to keep our photos; our memories, with you so that you will never forget.",
"Again, I love you, and thank you.Your little daughter always,Your little Dashie forever,Rainbow Dash.I set the note back into the page, flattening it with my hand as I felt the dried tear marks littering the paper.",
"I read the note over and over and over again, until I had it memorized.",
"Then, I turn the page, and was greeted with Dashie's filly smile.So now I sit here, looking through my photo album of our time together.",
"Her first bath, her first words, her first drawing, even her first preened feather, all in this book of memories.",
"Everything else in the house is gone, but what I had put into this book still remains.",
"I don't dare ever change that either, but I will continue to add to it.",
"To show that those years with her helped not only shape herself, but helped shape me as well.I am a new man from what I was fifteen years ago.",
"Changed, given another chance by a sheer miracle of fortunate events that transpired from somewhere I can't even speculate.",
"If I had never gone back and checked that box...",
"if I had done something different than I had...",
"could have changed everything between us.",
"I guess I'm lucky that it all worked out.",
"I can gladly say I have achieved my parent's only wish; for me to be happy.",
"Though I am saddened, I am still happy for the time I had with her.I now sit alone in this empty house, staring at my mother's rainbow picture with a smile plastered on my face; every time I see it, I think of Dashie.",
"I should be crying, I should feel horrible and want nothing but my daughter back.",
"And yet, I feel relieved to know that everything is alright.",
"She didn't run away, or leave on bad terms; she is gone, home, to where she belongs, and is safe.",
"I look back down to my photo album, turning to the page after our most recent photo.",
"The pages are blank.",
"I still have a lot of life ahead of me, and I plan to make the best of it.For myself.For my little Dashie.",
"The End."};
end
function Story:OnDisable()
	Story.Content = {}
	wipe(Story.Content)
end
